### ISSUE TITLE
Gradle dependencies

### ISSUE THREAD

**Issue by amouly** [mciruzzi/exercise-android#1]
Please, use Gradle and JCenter for dependencies, don't include the JARs inside the project, this produce  some overhead when pulling the project, and it's not necessary at this point.

http://gradleplease.appspot.com/

**Comment by mciruzzi** [comment]
I did it this way since assignment description said external libraries should be included in the deliverable. Done

**Comment by amouly** [comment]
@mciruzzi yeah, totally understand. Actually the challenge it's pretty old, like 2 o 3 years old, so at that time we were using Eclipse and Ant. At this point it's valuable if you "break the rules" and solve the challenge on your own way. This issues I've created are only minor details that can improve your code. Just implement the solution on your own way!
