### ISSUE TITLE
Alternative libraries

### ISSUE THREAD

**Issue by amouly** [mciruzzi/exercise-android#4]
You can replace Jackson library with GSON library, and Volley with Retrofit.

This is not a requirement, but this libraries helps to improve the separation of concerns and code quality. 

https://github.com/google/gson
http://square.github.io/retrofit/

**Comment by mciruzzi** [comment]
I've just read some blogs and seems like a nice step towards making it simplier. I should definitely try it. Specially Retrofit and maybe Picasso (https://www.bignerdranch.com/blog/solving-the-android-image-loading-problem-volley-vs-picasso/)

**Comment by amouly** [comment]
Yes, Picasso it's another cool library from the same people as Retrofit. This libraries are the most used ones.
